"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ROOM_DNE = exports.REQUEST_JOIN_ROOM = exports.NEW_ROOM_CREATED = exports.REQUEST_NEW_ROOM = exports.UPDATE_NAME_LIST = exports.OPP_EVALUATION = exports.EVALUATION = exports.GUESS = exports.DECLARE_NAME = void 0;
exports.DECLARE_NAME = "declare-name";
exports.GUESS = "guess";
exports.EVALUATION = "evaluation";
exports.OPP_EVALUATION = "opp-evaluation";
exports.UPDATE_NAME_LIST = "update-name-list";
exports.REQUEST_NEW_ROOM = "request-new-room";
exports.NEW_ROOM_CREATED = "new-room-created";
exports.REQUEST_JOIN_ROOM = "request-join-room";
exports.ROOM_DNE = "room-dne";
